module.exports = {
  row: [
    {
      "prefix_number": "A",
      "short_number": "64431",
      "event_timestamp": "14 January 2020",
      "event_timestamp_accuracy": "D",
      "event_banding_scheme": "NZNBBS Non-gamebird",
      "event_provider_number": "0001",
      "info_event_provider_name": "Gillian Vaughan",
      "event_reporter_number": "",
      "info_event_reporter_name": null,
      "info_other_name": "Susan Heron",
      "info_other_contact": null,
      "info_nznbbs_code": "3",
      "info_lookup_code": "Add/Change/Remove mark ",
      "mark_state_code": "",
      "event_type": "in-hand-post-change",
      "event_capture_type": "4. Caught in mist-net",
      "event_situation": "Wild",
      "info_species_common_name": "silvereye, tauhou",
      "info_species_scientific_name": "Zosterops lateralis",
      "species_code": "761",
      "characteristic_age": "A",
      "characteristic_sex": "U",
      "location_comment": "3. Waikato",
      "locality_general": "Miranda Orchard",
      "location_description": "Miranda Orchard, 1101 Miranda Rd",
      "latitude": "-37.178",
      "longitude": "175.293",
      "user_easting": null,
      "user_northing": null,
      "user_coordinate_system": "WGS84",
      "locality_accuracy": "10",
      "in_mark_config_material": null,
      "in_mark_config_form": null,
      "in_mark_config_fixing": null,
      "in_mark_config_uncertainty": null,
      "in_mark_config_left_tibia": null,
      "in_mark_config_left_tarsus": "B/R(ABC)W ",
      "in_mark_config_right_tibia": "",
      "in_mark_config_right_tarsus": "B/R/*",
      "in_mark_config_other_mark_type": null,
      "in_mark_config_other_mark_alpha": null,
      "in_characteristic_status_code": "alive",
      "in_characteristic_condition_code": "0. Good",
      "out_characteristic_status_code": null,
      "out_characteristic_condition_code": null,
      "characteristic_status_detail_1_code": null,
      "characteristic_status_detail_2_code": null,
      "info_notes": null,
      "info_sent_date": "25-May-20",
      "info_moratorium": "25-May-25",
      "characteristic_moult_p1": "3",
      "characteristic_moult_p2": "3",
      "characteristic_moult_p3": "1",
      "characteristic_moult_p4": "0",
      "characteristic_moult_p5": "0",
      "characteristic_moult_p6": "0",
      "characteristic_moult_p7": "0",
      "characteristic_moult_p8": "0",
      "characteristic_moult_p9": "0",
      "characteristic_moult_p10": "0",
      "info_moult_notes": null,
      "info_other_detail_10": null,
      "info_other_units_10": null,
      "info_other_value_10": null,
      "rowIndex": 5,
      "mark_config_material": null,
      "mark_config_form": null,
      "mark_config_fixing": null,
      "mark_config_uncertainty": null,
      "mark_config_left_tibia": "*/MDGSW(ABC)W",
      "mark_config_left_tarsus": "B/R(XYZ)W ",
      "mark_config_right_tibia": "MB(ABC)W",
      "mark_config_right_tarsus": "PO/NO(A-64432)K",
      "mark_config_other_mark_type": null,
      "mark_config_other_mark_alpha": null
    }
  ],
  row_against: [
    [
      {
        "side": "LEFT",
        "position": "TIBIA",
        "location_idx": 0,
        "mark_type": "LEG_BAND",
        "mark_form": null,
        "mark_material": "METAL",
        "mark_fixing": null,
        "colour": null,
        "text_colour": null,
        "alphanumeric_text": "a-64431"
      },
      {
        "side": "LEFT",
        "position": "TIBIA",
        "location_idx": 1,
        "mark_type": "LEG_BAND",
        "mark_form": null,
        "mark_material": "METAL",
        "mark_fixing": null,
        "colour": "DARK_GREEN_STRIPED_WHITE",
        "text_colour": "WHITE",
        "alphanumeric_text": "abc"
      },
      {
        "side": "LEFT",
        "position": "TARSUS",
        "location_idx": 0,
        "mark_type": "LEG_BAND",
        "mark_form": null,
        "mark_material": null,
        "mark_fixing": null,
        "colour": "BLUE",
        "text_colour": null,
        "alphanumeric_text": null
      },
      {
        "side": "LEFT",
        "position": "TARSUS",
        "location_idx": 1,
        "mark_type": "LEG_BAND",
        "mark_form": null,
        "mark_material": null,
        "mark_fixing": null,
        "colour": "RED",
        "text_colour": "WHITE",
        "alphanumeric_text": "xyz"
      },
      {
        "side": "RIGHT",
        "position": "TIBIA",
        "location_idx": 0,
        "mark_type": "LEG_BAND",
        "mark_form": null,
        "mark_material": "METAL",
        "mark_fixing": null,
        "colour": "BLUE",
        "text_colour": "WHITE",
        "alphanumeric_text": "abc"
      },
      {
        "side": "RIGHT",
        "position": "TARSUS",
        "location_idx": 0,
        "mark_type": "LEG_BAND",
        "mark_form": null,
        "mark_material": null,
        "mark_fixing": null,
        "colour": "PALE_ORANGE",
        "text_colour": null,
        "alphanumeric_text": null
      },
      {
        "side": "RIGHT",
        "position": "TARSUS",
        "location_idx": 1,
        "mark_type": "LEG_BAND",
        "mark_form": null,
        "mark_material": null,
        "mark_fixing": null,
        "colour": "FLUORESCENT_ORANGE",
        "text_colour": "BLACK",
        "alphanumeric_text": "a-64432"
      }
    ]
  ]
}